name: ubuntu-system-settings
version: 0
summary: The System Settings application for Ubuntu Touch.
description: The System Settings application for Ubuntu Touch.
# confinement: devmode  # use "strict" to enforce system access only via declared interfaces
confinement: strict
apps:
  ubuntu-system-settings:
    command: desktop-launch launcher system-settings
    plugs: [unity7, network, pulseaudio, home, gsettings, opengl, timezone-control, timeserver-control, network-manager, time-date-control]

parts:
  ubuntu-system-settings:
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
    plugin: cmake
    source: .
    build-packages:
      - dbus-test-runner
      - debhelper
      - dh-migrations
      - dh-python
      - python3-setuptools
      - python3-all
      - gdb
      - intltool
      - libaccountsservice-dev
      - libandroid-properties-dev
      - libclick-0.4-dev
      - libgeonames-dev
      - libglib2.0-dev
      - libevdev-dev
      - libicu-dev
      - libnm-glib-dev
      - libpolkit-agent-1-dev
      - libqmenumodel-dev
      - libtrust-store-dev
      - libudev-dev
      - libunity-api-dev
      - libupower-glib-dev
      - pkg-config
      - qml-module-qtcontacts
      - qml-module-qtsysteminfo
      - qml-module-ubuntu-connectivity
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-ubuntu-download-manager0.1
      - qtdeclarative5-ubuntu-history0.1
      - qtdeclarative5-ubuntu-keyboard-extensions0.1
      - libapt-pkg-dev
      - libgnome-desktop-3-dev
      - libgsettings-qt-dev
    # stage:
    #   - -usr/share/pkgconfig/xkeyboard-config.pc
    #   - -usr/share/pkgconfig/shared-mime-info.pc
    stage-packages:
      - accountsservice
      - accountsservice-ubuntu-schemas
      - aethercast
      - bluez
      - click
      - dbus-property-service
      - gsettings-desktop-schemas
      - gsettings-ubuntu-schemas
      - indicator-bluetooth
      - indicator-datetime
      - indicator-network
      - indicator-power
      - powerd
      - qmenumodel-qml
      - qml-module-biometryd
      - qml-module-qt-labs-folderlistmodel
      - qml-module-ubuntu-connectivity
      - qml-module-qtmultimedia
      - qtdeclarative5-gsettings1.0
      - qtdeclarative5-ofono0.2
      - qml-module-qtsysteminfo
      - qtdeclarative5-ubuntu-content1
      - qtdeclarative5-ubuntu-settings-components
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
      - suru-icon-theme
      - whoopsie-preferences
      - libsystemsettings1
      - system-image-dbus
      - ubuntu-keyboard-data
      - urfkill
      - python3
      - python3-gi
      - python3-dbus
      - python3-xdg
      - gir1.2-glib-2.0
    # snap:
    #   - -usr/lib/python3
    #   - -usr/share/doc
    #   - -usr/include
    after: [desktop/qt5]

  launcher:
    plugin: dump
    source: snap
    organize:
      launcher: bin/launcher
